<x-layout>
    @include('partials._hero')
    @include('partials._services-carousel')
    @include('partials._about-section')
    @include('partials._problem-value-statement')
    @include('partials._assessment-cta')
    @include('partials._approach-section')
    @include('partials._approach-steps')
    @include('partials._portfolio-section')
    @include('partials._cta-section')
    @include('partials._stat-section')
    @include('partials._footer')
</x-layout>
